# Generated by Django 4.2.6 on 2023-11-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_rename_student_stay_hostel_student_stay_and_more'),
        ('school_fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='Fee_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finance',
            name='Fee_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finance',
            name='Total_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finance',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_register.student'),
        ),
    ]
