# Generated by Django 4.2.6 on 2023-11-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='student_stay',
            new_name='Student_stay',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.AddField(
            model_name='hostel',
            name='Members_in_room',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Student',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='student_register.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='Intake_year',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Mobile_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='Reg_no',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Student_email',
            field=models.EmailField(default=0, max_length=20),
        ),
    ]
